### ISSUE TITLE
Computer Canvas issue

### ISSUE THREAD

**Issue by AmnaIqbal-01** [adrianhajdin/project_3D_developer_portfolio#168]
Hey , I am trying to load the computer canvas in my hero file, but it shows the following errors.

The above error occurred in the <div> component:

    at div
    at Loader
    at Suspense
    at Suspense
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/chunk-CJBKLY4X.js?v=0839ad62:47830:5)
    at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-CJBKLY4X.js?v=0839ad62:49450:21)
    at Provider (http://localhost:5173/node_modules/.vite/deps/chunk-CJBKLY4X.js?v=0839ad62:49117:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
overrideMethod @ hook.js:591
Show 1 more frame
Show less
2react-three-fiber.esm.js:241  Uncaught Error: R3F: Div is not part of the THREE namespace! Did you forget to extend? See: https://docs.pmnd.rs/react-three-fiber/api/objects#using-3rd-party-objects-declaratively
    at createInstance (events-321b05fb.esm.js:36:15)
    at completeWork (react-reconciler.development.js:10851:28)
    at completeUnitOfWork (react-reconciler.development.js:18725:16)
    at performUnitOfWork (react-reconciler.development.js:18697:5)
    at workLoopSync (react-reconciler.development.js:18597:5)
    at renderRootSync (react-reconciler.development.js:18565:7)
    at recoverFromConcurrentError (react-reconciler.development.js:17948:20)
    at performConcurrentWorkOnRoot (react-reconciler.development.js:17848:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
hook.js:591  The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://localhost:5173/node_modules/.vite/deps/chunk-CJBKLY4X.js?v=0839ad62:49665:3)
    at FiberProvider (http://localhost:5173/node_modules/.vite/deps/chunk-CJBKLY4X.js?v=0839ad62:49450:21)
    at CanvasWrapper
    at ComputersCanvas (http://localhost:5173/src/components/canvas/Computers.jsx?t=1727966459699:84:35)
    at section
    at Hero
    at div
    at div
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=0839ad62:4474:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=0839ad62:5219:5)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ hook.js:591
Show 1 more frame
Show less
react-dom.development.js:26962  Uncaught Error: R3F: Div is not part of the THREE namespace! Did you forget to extend? See: https://docs.pmnd.rs/react-three-fiber/api/objects#using-3rd-party-objects-declaratively
    at createInstance (events-321b05fb.esm.js:36:15)
    at completeWork (react-reconciler.development.js:10851:28)
    at completeUnitOfWork (react-reconciler.development.js:18725:16)
    at performUnitOfWork (react-reconciler.development.js:18697:5)
    at workLoopSync (react-reconciler.development.js:18597:5)
    at renderRootSync (react-reconciler.development.js:18565:7)
    at recoverFromConcurrentError (react-reconciler.development.js:17948:20)
    at performConcurrentWorkOnRoot (react-reconciler.development.js:17848:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    
![image](https://github.com/user-attachments/assets/1f8a89d6-7340-4dc3-8158-94fa85877bb3)

**Comment by AmnaIqbal-01** [comment]
nvm, solved the issue, my loader class was empty.

**Comment by AmnaIqbal-01** [comment]
nvm, my loader class was empty, solved the issue.
