### ISSUE TITLE
React tilt issue

### ISSUE THREAD

**Issue by yeshwantthota** [adrianhajdin/project_3D_developer_portfolio#38]
Screen becomes blank when react tilt is used in About.js page

**Comment by Smr777** [comment]
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?v=2372342d' does not provide an export named 'default' (at About.jsx:11:8)
yup facing this issue

**Comment by niladrix719** [comment]
import { tilt } from 'tilt'; not working

**Comment by yeshwantthota** [comment]
@niladrix719 close and restart the server, it works for me

**Comment by niladrix719** [comment]
this is what i am getting after restart

![Screenshot from 2023-04-02 17-25-07](https://user-images.githubusercontent.com/91966855/229351202-5328288a-e161-42d0-a742-3320af09e2b8.png)
![image](https://user-images.githubusercontent.com/91966855/229351215-05f12347-9879-4197-ba69-a3aeeab9bd93.png)

**Comment by niladrix719** [comment]
oh thanks mate @yeshwantthota

**Comment by Ethan9030** [comment]
It happens to me when I refresh the page. I restart the server but it still keep blank.

**Comment by yeshwantthota** [comment]
> It happens to me when I refresh the page. I restart the server but it still keep blank.

what error you are getting in the console?

**Comment by Ethan9030** [comment]
There were no errors on the console. The dev tools show it seems nothing was loaded. I just type the code again and it works😂.

**Comment by elvind007** [comment]
Use react-parallax-tilt instead

Uninstall react tilt and install parallax tilt (npm install react-parallax-tilt) ,

 import is almost the same, use  import Tilt from 'react-parallax-tilt';

**Comment by Noman-Nom** [comment]
npm install react-parallax-tilt
import Tilt from 'react-parallax-tilt';
replace // import Tilt from "react-tilt";
your code will working fine and please mark the issue solved

**Comment by talhanoman** [comment]
npm install react-tilt
import { Tilt } from "react-tilt";

**Comment by sedeeman** [comment]
> Use react-parallax-tilt instead
> 
> Uninstall react tilt and install parallax tilt (npm install react-parallax-tilt) ,
> 
> import is almost the same, use import Tilt from 'react-parallax-tilt';

This is working, Thanks for sharing

**Comment by CoorayNTL** [comment]
> > It happens to me when I refresh the page. I restart the server but it still keep blank.
> 
> what error you are getting in the console?



> import { Tilt } from "react-tilt"; it should be like this

it's working

**Comment by GeryAdhane** [comment]
> import { Tilt } from "react-tilt"; it should be like this

Thank you, I have been struggling for two days only to solve this error. This solved it. Than you man.

**Comment by Noman-Nom** [comment]
welcome bro

**Comment by johnvnel** [comment]
@Noman-Nom thanks for the help bro. but can you explain why that happens?

**Comment by Rakeshkraki** [comment]
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?v=3743f72a' does not provide an export named 'default' (at Works.jsx:2:8)
