### ISSUE TITLE
Hello Adrian, I have problem with About.jsx file code please if you can help me with this error?   ....

### ISSUE THREAD

**Issue by davorbu** [adrianhajdin/project_3D_developer_portfolio#5]
Failed to resolve import "react-tilt" from "src\components\About.jsx". Does the file exist? 

D:/myportfolio/src/components/About.jsx:2:17
15 |  }
16 |  import React from "react";
17 |  import Tilt from "react-tilt";
   |                    ^
18 |  import { motion } from "framer-motion";
19 |  import { styles } from "../styles";
    at formatError (file:///D:/myportfolio/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
    at TransformContext.error (file:///D:/myportfolio/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
    at normalizeUrl (file:///D:/myportfolio/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.transform (file:///D:/myportfolio/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
    at async Object.transform (file:///D:/myportfolio/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
    at async loadAndTransform (file:///D:/myportfolio/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

**Comment by davorbu** [comment]
![Snimka zaslona (88)](https://user-images.githubusercontent.com/73069914/222965742-a146fff9-91d1-4f2e-a8c2-7233d4f405ae.png)

**Comment by TauqeerHusain** [comment]
bro might be you dont installed the package of react-tilt

**Comment by davorbu** [comment]
I search and search where I got stuck and I managed to solve the problem before I saw your answer. 
Thank you so much Adrian. I like your style how you working, and this is great!!

**Comment by davorbu** [comment]
You are from Zagreb or?

**Comment by TauqeerHusain** [comment]
no i am tauqeer

**Comment by bottercode** [comment]
hey! can you assign me this. I would like to work on this

**Comment by TauqeerHusain** [comment]
i already work all code is working

**Comment by bottercode** [comment]
Okay!

**Comment by SalmanMujtaba** [comment]
Let's close this issue if it is already working. Thanks!

**Comment by Sk-hub462** [comment]
How did you resolve this error?

**Comment by hady-dev** [comment]
> How did you resolve this error?

"npm install react-tilt"

The problem is that react-tilt is not installed properly.

**Comment by 023PrashantSharma** [comment]
>>npm install react-parallax-tilt
import Tilt from 'react-parallax-tilt';
replace // import Tilt from "react-tilt";
your code will working fine and please mark the issue solved

**Comment by Noman-Nom** [comment]
> > > npm install react-parallax-tilt
> > > import Tilt from 'react-parallax-tilt';
> > > replace // import Tilt from "react-tilt";
> > > your code will working fine and please mark the issue solved

issue solved

**Comment by MuhammadAnabHussain** [comment]
i have problem with same issue what can i do for this i installed npm install react-tilt but it got me this error 
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?t=1694334760740&v=a57d4cb8' does not provide an export named 'default' (at About.jsx:2:8)

**Comment by 19cs193** [comment]
nope not working tried but not working white screen
with:  Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?t=1694334760740&v=a57d4cb8' does not provide an export named 'default' (at About.jsx:2:8)

error in console log

**Comment by s0rryFSU** [comment]
> nope not working tried but not working white screen with: Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?t=1694334760740&v=a57d4cb8' does not provide an export named 'default' (at About.jsx:2:8)
> 
> error in console log

im not getting the syntax error but I am getting a white screen.

**Comment by s0rryFSU** [comment]
> nope not working tried but not working white screen with: Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?t=1694334760740&v=a57d4cb8' does not provide an export named 'default' (at About.jsx:2:8)
> 
> error in console log



> i have problem with same issue what can i do for this i installed npm install react-tilt but it got me this error Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-tilt.js?t=1694334760740&v=a57d4cb8' does not provide an export named 'default' (at About.jsx:2:8)

to the last 2 commenters, as indicated in the responses above use
npm install react-parallax-tilt and change the import.
